services:
  redis:
    image: redis:7-alpine
    # Remove port mapping to prevent external access
    # ports:
    #   - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-dev_password_123}

volumes:
  redis_data:
